version: "3.7"
services:
  db:
    image: postgres:12.1

  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: unless-stopped

  web:
    image: trivia-web
    build:
      context: .
      dockerfile: ./web.dockerfile
      target: dev
    volumes:
      - .:/app
    env_file: .env
    environment:
      PORT: 8000
    ports:
      - 8060:8000
      - 8061:8080

  api:
    image: trivia-api
    build:
      context: .
      dockerfile: ./app.dockerfile
    volumes:
      - .:/app
    command: python app.py
    env_file: .env
    environment:
      PORT: 8180
    ports:
      - 8180:8180
